export const tabs = [
  {
    id: 0,
    label: "Clinical Pathology",
    color: "bg-[#1d5fb9]",
    borderColor: "border-[#1d5fb9]",
    textColor: "text-[#1d5fb9]",
    content: {
      paragraphs: [
        // "We are the UK's best and most-trusted laboratory, providing home DNA, Drug, Alcohol and Health testing services.",
        // "Whether you need a paternity test for your own peace of mind, or simply want to check up on your health, we have a range of tests available to suit your needs. We also offer legally admissible DNA, Drug and Alcohol testing for private legal matters.",
        // "Better still, all our tests are performed in the UK at our state-of-the-art laboratory, so your samples will never be sent abroad.",
      ],
      tags: [
        "Microbiology",
        "Hermatology",
        "Chemistry",
        "Immunology",
        "Hispathology",
        "Molecular Diagnostics",
      ],
      cta: "Book appointment",
    },
  },
  {
    id: 1,
    label: "DNA Testing",
    color: "bg-[#b356a1]",
    borderColor: "border-[#b356a1]",
    textColor: "text-[#b356a1]",
    content: {
      paragraphs: [],
      tags: ["Paternity testing", "Maternity Testing", "Prenatal screening"],
      cta: "Get a Quote",
    },
  },
  {
    id: 2,
    label: "General Health screening",
    color: "bg-[#e56000]",
    borderColor: "border-[#e56000]",
    textColor: "text-[#e56000]",
    content: {
      paragraphs: [],
      tags: [
        "Diabetes and Hypertension",
        "Kidney, Heart and Liver",
        "Cancer screening",
        "Pre-employment screening",
        "Pre-school screening",
        "Travel screening",
      ],
      cta: "Get a Quote",
    },
  },
  {
    id: 3,
    label: "Drug Testing",
    color: "bg-[#0094a8]",
    borderColor: "border-[#0094a8]",
    textColor: "text-[#0094a8]",
    content: {
      paragraphs: ["Designed for workplaces, schools and homes. For legal and peace of mind"],
      tags: [
        "Cannabis",
        "Amohetamine",
        "Cocaine",
        "Benzodizepam",
        "Methadone",
        "Opiate (Heroine)",
        "Tramadol",
        "Bupremorphine",
      ],
      cta: "Book appointment",
    },
  },
  {
    id: 4,
    label: "Sexually Transmitted Infection test ",
    color: "bg-[#9B0100]",
    borderColor: "border-[#9B0100]",
    textColor: "text-[#9B0100]",
    content: {
      paragraphs: ["Designed for workplaces, schools and homes. For legal and peace of mind"],
      tags: ["HIV", "Gonorrhea", "Syphillis", "Chlamydia", "Herpes", "OHepatitis B and C"],
      cta: "Book appointment",
    },
  },
]

export const reviews = [
  {
    id: 1,
    title: "They are reliable",
    body: "For the past four years, this lab has been my go-to for all my tests. Results are always ready quickly, and the staff treat you with respect and kindness. Truly dependable service.",
    author: "A. D",
    date: "24 Dec, 2025",
  },
  {
    id: 2,
    title: "Express Clinical Laborat...",
    body: "Express Clinical Laboratory has earned my trust over the years. Their speed, accuracy, and courteous staff make every visit smooth and reassuring.",
    author: "E. A",
    date: "26 April, 2026",
  },
  {
    id: 3,
    title: "Supportive Patient Care",
    body: "We have consistently referred samples to Express Clinical Laboratory, and their quality and reliability have greatly supported our patient care. Their professionalism and expertise are commendable.",
    author: "",
    date: "12 Jan, 2026",
  },
  {
    id: 4,
    title: "A valuable partner",
    body: "Express Clinical Laboratory has been a valuable partner in diagnostics. Their timely results, consistency, and high standards have strengthened our clinical decision-making.",
    author: "",
    date: "24 April, 2026",
  },
  {
    id: 5,
    title: "Commitment to Accuracy",
    body: "Our collaboration with Express Clinical Laboratory has been excellent. Their commitment to quality and accuracy continues to enhance the care we provide to our patients.",
    author: "H. O",
    date: "15 Aug, 2025",
  },
  {
    id: 6,
    title: "Confidential and Professional",
    body: "I used their DNA testing service and was impressed by how confidential and professional the entire process was. The results came faster than expected. Highly satisfied.",
    author: "M. S",
    date: "02 Feb, 2026",
  },
  {
    id: 7,
    title: "Complete Peace of Mind",
    body: "Express Clinical Laboratory handled my paternity test with complete privacy and efficiency. The quick turnaround time gave me peace of mind.",
    author: "",
    date: "19 Nov, 2025",
  },
  {
    id: 8,
    title: "Confidence in My Health",
    body: "As someone managing diabetes and hypertension, I rely on Express Clinical Laboratory for routine monitoring. Their accuracy and consistency give me confidence in my health.",
    author: "R. K",
    date: "10 Mar, 2026",
  },
  {
    id: 9,
    title: "Excellent Routine Service",
    body: "I regularly check my blood sugar and organ function here, and the service has been excellent. I recommend this lab to anyone managing chronic conditions.",
    author: "",
    date: "05 Oct, 2025",
  },
  {
    id: 10,
    title: "Instrumental Health Support",
    body: "They’ve been instrumental in helping me stay on top of my health. Reliable results, friendly staff, and a smooth process every time.",
    author: "J. B",
    date: "22 Jan, 2026",
  },
  {
    id: 11,
    title: "Stress-Free Home Service",
    body: "I appreciated the confidentiality and professionalism of their STI testing service. The home service option made everything convenient and stress-free.",
    author: "L. W",
    date: "14 Sep, 2025",
  },
  {
    id: 12,
    title: "Discreet and Reliable",
    body: "Express Clinical Laboratory handled my tests with complete privacy. Their discreet approach and reliable results gave me confidence.",
    author: "",
    date: "30 Mar, 2026",
  },
  {
    id: 13,
    title: "Comfortable Experience",
    body: "Their home service and strict confidentiality stood out to me. I felt comfortable and well cared for throughout the process.",
    author: "C. T",
    date: "11 Dec, 2025",
  },
]
